export enum EspecialidadEmpleado{
    PELUQUERIA = 'PELUQUERIA',
    MANICURA = 'MANICURA',
    PEDICURA = 'PEDICURA',
    ESTETICA_FACIAL = 'ESTETICA_FACIAL',
    MASAJES = 'MASAJES',
    DEPILACION = 'DEPILACION',
    MAQUILLAJE = 'MAQUILLAJE',
    COSMETOLOGIA = 'COSMETOLOGIA',
    MICROPIGMENTACION = 'MICROPIGMENTACION',
    PESTAÑAS_Y_CEJAS = 'PESTAÑAS_Y_CEJAS',
    SPA = 'SPA',
    RECEPCION = 'RECEPCION',
    MULTIFUNCIONAL = 'MULTIFUNCIONAL'
}