export enum EstadoTurno{
    CONFIRMADO = 'CONFIRMADO',
    CANCELADO = 'CANCELADO',
    PENDIENTE = 'PENDIENTE',
    EN_CURSO = 'EN_CURSO',
    REPROGRAMADO = 'REPROGRAMADO',
    AUSENTE = 'AUSENTE',
    FINALIZADO = 'FINALIZADO',
    RECHAZADO = 'RECHAZADO'
}