spring.application.name=BeautyManager

# Puerto del servidor
server.port=8080

# Configuración de Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Perfil activo por defecto (puede ser dev)
spring.profiles.active=dev

jwt.private-key-path=jwtKeys/private_key.pem
jwt.public-key-path=jwtKeys/public_key.pem

jwt.issuer=BeautyManager
jwt.audience=BeautyManager-Web
jwt.expiration-hours=4

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mariajosecaballero001@gmail.com
spring.mail.password=auupamiihrcpnzpo


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.starttls.required=true


spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000